name: pub_doctor
description: Dependency health diagnostics and risk scoring for Dart & Flutter projects.
version: 0.0.2
repository: https://github.com/Sahad2701/pub_doctor
issue_tracker: https://github.com/Sahad2701/pub_doctor/issues
topics:
  - dart
  - flutter
  - cli
  - dependency-analysis
  - dependency-management

icon: icon.png

screenshots:
  - description: 'Running pub_doctor health check on a terminal'
    path: screenshots/run.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.7.0
  yaml: ^3.1.3
  http: ^1.6.0
  pub_semver: ^2.2.0
  path: ^1.9.1
  collection: ^1.19.1
  crypto: ^3.0.7
  lints: ^6.1.0

dev_dependencies:
  test: ^1.29.0
  mockito: ^5.6.3
  build_runner: ^2.11.1

executables:
  pub_doctor: pub_doctor
