name: test_update
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.10.9

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^0.13.0
  provider: ^6.1.5+1
  shared_preferences: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
